apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: P951FEA4DE68E13C5
    access: proxy
    editable: true
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: nso
      tlsSkipVerify: true
    secureJsonData:
      token: {TOKEN}

  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET

